# Generated by Django 3.0.3 on 2020-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfstracker', '0003_auto_20200801_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsdb',
            name='attachement',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='rfsreqfile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
