# Generated by Django 3.0.3 on 2020-08-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfstracker', '0004_auto_20200801_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsdb',
            name='attachement',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='rfsreqfile',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
