# Generated by Django 3.0.3 on 2020-08-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfstracker', '0006_auto_20200803_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsdb',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='oppnumber',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
