# Generated by Django 3.0.3 on 2020-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfstracker', '0007_auto_20200803_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsdb',
            name='slno',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsdb',
            name='queue',
            field=models.CharField(choices=[('sales', 'Sales Queue'), ('solutions', 'Solutions Queue'), ('projectmgmt', 'ProjectMgmt Queue'), ('servicemgmt', 'ServiceMgmt Queue'), ('pricing', 'Pricing Queue'), ('completed', 'Completed')], default='sales', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='queue',
            field=models.CharField(choices=[('sales', 'Sales Queue'), ('solutions', 'Solutions Queue'), ('projectmgmt', 'ProjectMgmt Queue'), ('servicemgmt', 'ServiceMgmt Queue'), ('pricing', 'Pricing Queue'), ('completed', 'Completed')], default='sales', max_length=50),
        ),
    ]
