# Generated by Django 3.0.3 on 2020-08-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfstracker', '0008_auto_20200803_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsdb',
            name='slno',
        ),
    ]
